### ISSUE TITLE
是采用gitbook方式做的？

### ISSUE THREAD

**Issue by bubifengyun** [forecho/yii2-practice-book#4]
我的网站接近尾声，正在做权限控制部分。年后应该有时间整理文档了。我也试试安装gitbook试试。我一直在linux deepin下开发，做的文档一般也都是在deepin下的操作方式。不过没有太大关系，合作愉快。

**Comment by forecho** [comment]
嗯，是按照 gitbook 方式写的，但是我直接用 sublime 写的文章，到时候一样可以用 gitbook 生成mobi 等其他格式。

**Comment by bubifengyun** [comment]
我是使用vscode写markdown文件的。编辑器不影响生成吧。都是utf-8编码.

**Comment by forecho** [comment]
不影响吧，主要是 SUMMARY.md 这个文件，文件名必须是这个，里面写好路径。
